name: Create or Update Draft Release

on:
  push:
    branches:
    - 1.4.x
  repository_dispatch:
    types: [ version-bump ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release to cut (e.g. 1.2.3)'
        required: false

# TODO REMOVE
concurrency: release

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # gets full history
        fetch-tags: true

    # TODO 1- why is main draft release not picking up the latest tag we create - v1.5.0
    # TODO NOT DELETING previously drafted
    # TODO don't draft a release if the new version is the same as last release
    - name: Reset Draft Release
      id: reset
      uses: paketo-buildpacks/github-config/actions/release/reset-draft@main
      with:
        repo: ${{ github.repository }}
        token: ${{ github.token }}
    - name: Get Latest Tag on Branch ${{ github.ref_name }}
      id: latest
      run: |
        # Get the latest tag in the version line
        # If working off main branch, get the latest tag
        # If working off a version line branch (ex. 1.3.x), get the latest tag in the version line (v1.3.*)
        tag_search=""
        if [[ ${{ github.ref_name }} != "main" ]]; then
          # convert version line into tag search: 1.3.x -> v1.3.*
          tag_search=$(echo ${{ github.ref_name }} | awk -F'[.]' '{printf("v%d.%d.*\n", $1, $2)}')
        fi
        version=$(git tag ${tag_search} --sort "version:refname" --merged | tail -n1)
        echo $version
        echo "version=${version}" >> "$GITHUB_OUTPUT"
    - name: Calculate Semver Tag
      if: github.event.inputs.version == ''
      id: semver
      uses: paketo-buildpacks/github-config/actions/tag/calculate-semver@semver-only
      with:
        repo: ${{ github.repository }}
        token: ${{ github.token }}
        ref-name: ${{ github.ref_name }}
        latest-version: ${{ steps.latest.outputs.version }}
    - name: Set Release Tag
      id: tag
      run: |
        tag="${{ github.event.inputs.version }}"
        if [ -z "${tag}" ]; then
          tag="${{ steps.semver.outputs.tag }}"
        fi
        echo "tag=${tag}" >> "$GITHUB_OUTPUT"
    - name: Create Release
      uses: paketo-buildpacks/github-config/actions/release/create@main
      with:
        repo: ${{ github.repository }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        tag_name: v${{ steps.tag.outputs.tag }}
        target_commitish: ${{ github.sha }}
        name: v${{ steps.tag.outputs.tag }}
        draft: true
