name: Create or Update Draft Release

on:
  push:
    branches:
    - main
  repository_dispatch:
    types: [ version-bump ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release to cut (e.g. 1.2.3)'
        required: false

concurrency: release

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # gets full history
        fetch-tags: true

    - name: Reset Draft Release
      id: reset
      uses: paketo-buildpacks/github-config/actions/release/reset-draft@main
      with:
        repo: ${{ github.repository }}
        token: ${{ github.token }}
    - name: Get Latest Release
      id: latest
      run: |
        version=$(git describe --tags --abbrev=0 ${{ github.ref_name }})
        echo $version
    - name: Increment Tag
      id: increment
      if: github.event.inputs.version == ''
      uses: paketo-buildpacks/github-config/actions/tag/increment-tag@main
      with:
        current_version: ${{ steps.reset.outputs.current_version }}
    - name: Set Release Tag
      id: tag
      run: |
        tag="${{ github.event.inputs.version }}"
        if [ -z "${tag}" ]; then
          tag="${{ steps.increment.outputs.tag }}"
        fi
        echo "tag=${tag}" >> "$GITHUB_OUTPUT"
    - name: Create Release
      uses: paketo-buildpacks/github-config/actions/release/create@main
      with:
        repo: ${{ github.repository }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        tag_name: v${{ steps.tag.outputs.tag }}
        target_commitish: ${{ github.sha }}
        name: v${{ steps.tag.outputs.tag }}
        draft: true
