name: Update Dependencies From Metadata (Retrieve, Metadata, Compile, Test, Create PR)

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *' # TODO remove this, just for testing

jobs:
  version-line:
    name: Setup Version Line Branch Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
    steps:
      - name: Setup Matrix Array
        id: setup
        run: |
          branches=($(git branch -a | grep -P "\d+\.\d+\.x" | sort -V | tail -n1 | sed -e 's/remotes\/origin\///g'))
          branches+=('main')
          json_branches=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${branches[@]}")
          echo $json_branches
          echo "matrix=$json_branches" >> "$GITHUB_OUTPUT"

  assemble:
    name: Update buildpack.toml
    needs:
      - version-line
    # Update buildpack.toml only if ALL of the following conditions are met:
    #   (1) Retrieval step has succeeded and has found at least 1 new version
    #   (2) Testing step has succeeded OR been skipped
    #   (3) Compilation/Testing step has succeeded OR been skipped
    #   (4) Update metadata step has succeeded OR been skipped
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.version-line.outputs.matrix) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Checkout Branch
        uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
        with:
          branch: automation/dependencies/update-from-metadata-on-${{ matrix.branch }}
